import { useState } from 'react';
import { Conversation, Modal, NotificationPanel, useDashboardState } from './dashboard-core';

const fields = ['Yazılım / Bilgisayar', 'Elektrik-Elektronik', 'Makine', 'Endüstri', 'İnşaat', 'Kimya', 'Biyomedikal', 'Havacılık ve Uzay', 'Gemi ve Deniz'];
const universities = [{ name: 'İTÜ', city: 'İstanbul', rank: '2.000', field: 'Bilgisayar Müh.' }, { name: 'ODTÜ', city: 'Ankara', rank: '3.000', field: 'Elektrik-Elektronik Müh.' }, { name: 'Bilkent', city: 'Ankara', rank: '5.000', field: 'Endüstri Müh.' }];
const mentors = [{ id: 'm1', name: 'Ece Yıldız', job: 'Yazılım Mühendisi', company: 'Teknoloji şirketi' }, { id: 'm2', name: 'Mert Deniz', job: 'Elektrik Mühendisi', company: 'Enerji şirketi' }, { id: 'm3', name: 'Sena Akın', job: 'Endüstri Mühendisi', company: 'Danışmanlık' }];
const peers = ['Kaan Arda', 'Zeynep Demir', 'Deniz Ekin'];

export default function CandidateDashboard() {
  const [tab, setTab] = useState('overview'); const [schoolView, setSchoolView] = useState('peers'); const [modal, setModal] = useState(null); const [selectedField, setSelectedField] = useState(fields[0]); const [requests, setRequests] = useState([]); const [profile, setProfile] = useState({ net: '', about: '', target: '' }); const [noticeOpen, setNoticeOpen] = useState(false); const { state, notify, markAllRead } = useDashboardState();
  const navigation = [['overview', 'Panel'], ['school', 'Okul ağım'], ['discover', 'Alan keşfi'], ['university', 'Üniversiteler'], ['mentors', 'Mentorlar'], ['assistant', 'AI danışman'], ['profile', 'Profilim']];
  const request = (mentor) => { setRequests((items) => items.includes(mentor.id) ? items : [...items, mentor.id]); notify(`${mentor.name} için mentor isteği gönderildi.`, 'mentors'); setModal(null); };
  const close = () => setModal(null);
  return <div className="dashboard"><aside className="dashboard-nav"><a className="brand" href="/">EngineersPath</a><p className="muted">Aday öğrenci</p><nav>{navigation.map(([id, text]) => <button className={'nav-button ' + (tab === id ? 'active' : '')} key={id} onClick={() => setTab(id)}>{text}</button>)}</nav><button className="nav-button" onClick={() => localStorage.clear()}>Çıkış yap</button></aside><main className="dashboard-main"><header className="dashboard-heading"><div><p className="eyebrow">Aday öğrenci alanı</p><h1>Hedefini keşfet</h1></div><button className="button" onClick={() => setNoticeOpen(!noticeOpen)}>Bildirimler · {state.notifications.filter((item) => !item.read).length}</button></header>{noticeOpen && <NotificationPanel navigate={setTab} close={() => setNoticeOpen(false)} />}
    {tab === 'overview' && <section className="dashboard-grid"><article className="surface dashboard-card"><span className="tag">AI danışman</span><h2>Mühendislik yolunu planla</h2><p className="muted">İlgi alanlarını, derslerini ve hedefini değerlendir.</p><button className="button primary" onClick={() => setTab('assistant')}>Danışmana sor</button></article><article className="surface dashboard-card"><span className="tag">Alan keşfi</span><h2>9 mühendislik alanı</h2><p className="muted">Becerileri, dersleri ve kariyer imkanlarını karşılaştır.</p><button className="button" onClick={() => setTab('discover')}>Alanları aç</button></article><article className="surface dashboard-card"><span className="tag">Mentorluk</span><h2>{requests.length} mentor isteği</h2><p className="muted">Üniversite ve sektör deneyimini doğrudan dinle.</p><button className="button" onClick={() => setTab('mentors')}>Mentorları gör</button></article></section>}
    {tab === 'discover' && <section><label className="field">Mühendislik alanı<select value={selectedField} onChange={(e) => setSelectedField(e.target.value)}>{fields.map((field) => <option key={field}>{field}</option>)}</select></label><div className="dashboard-grid">{fields.map((field) => <article className="surface dashboard-card" key={field}><span className="tag">Mühendislik</span><h2>{field}</h2><p className="muted">Temel dersler, beceriler, çalışma alanları ve gelecek fırsatları.</p><button className="button primary" onClick={() => setModal({ type: 'field', field })}>Detaylı incele</button></article>)}</div></section>}
    {tab === 'university' && <section><div className="tabs"><button aria-selected="true">Tüm üniversiteler</button><button aria-selected="false">Karşılaştırma</button></div><div className="dashboard-grid">{universities.map((uni) => <article className="surface dashboard-card" key={uni.name}><span className="tag">Hedef sıralama · {uni.rank}</span><h2>{uni.name}</h2><p className="muted">{uni.city} · {uni.field}</p><div className="button-row"><button className="button" onClick={() => setModal({ type: 'university', uni })}>Bölüm detayı</button><button className="button primary" onClick={() => setModal({ type: 'universityMentors', uni })}>Mentorları gör</button></div></article>)}</div></section>}
    {tab === 'mentors' && <section><div className="tabs"><button aria-selected="true">Tüm mentorlar</button><button aria-selected="false">Kabul edilenler</button><button aria-selected="false">Sohbetler</button></div><div className="dashboard-grid">{mentors.map((mentor) => <article className="surface dashboard-card" key={mentor.id}><span className="tag">{mentor.company}</span><h2>{mentor.name}</h2><p className="muted">{mentor.job}</p><div className="button-row"><button className="button" onClick={() => setModal({ type: 'mentor', mentor })}>Profili gör</button><button className="button primary" disabled={requests.includes(mentor.id)} onClick={() => setModal({ type: 'request', mentor })}>{requests.includes(mentor.id) ? 'İstek gönderildi' : 'İstek gönder'}</button></div></article>)}</div></section>}
    {tab === 'school' && <section><div className="tabs">{[['peers','Aday arkadaşlar'],['announcements','Duyurular'],['clubs','Çalışma kulüpleri'],['chat','Sohbetler']].map(([id,text]) => <button aria-selected={schoolView === id} key={id} onClick={() => setSchoolView(id)}>{text}</button>)}</div>{schoolView === 'peers' && <div className="dashboard-grid">{peers.map((name) => <article className="surface dashboard-card" key={name}><span className="tag">12. sınıf · çevrimiçi</span><h2>{name}</h2><p className="muted">Mühendislik hedefi ve tercih hazırlığı.</p><button className="button primary" onClick={() => setModal({ type: 'chat', name })}>Sohbet başlat</button></article>)}</div>}{schoolView === 'announcements' && <section className="dashboard-grid">{['Tercih webinarı · Cumartesi 14.00', 'Deneme analiz buluşması', 'Mühendislik tanıtım günü'].map((text) => <article className="surface dashboard-card" key={text}><span className="tag">Duyuru</span><h2>{text}</h2><button className="button" onClick={() => notify(`${text} kaydedildi.`, 'school')}>Hatırlat</button></article>)}</section>}{schoolView === 'clubs' && <section className="dashboard-grid">{['Robotik çalışma grubu', 'YKS sayısal kulübü', 'İngilizce teknik okuma'].map((text) => <article className="surface dashboard-card" key={text}><span className="tag">Kulüp</span><h2>{text}</h2><p className="muted">Haftalık çevrimiçi çalışma ve akran desteği.</p><button className="button primary" onClick={() => notify(`${text} kulübüne katıldın.`, 'school')}>Katıl</button></article>)}</section>}{schoolView === 'chat' && <Conversation thread="candidate-school" title="Okul ağı sohbetleri" />}</section>}
    {tab === 'assistant' && <Conversation thread="candidate-ai" title="AI mühendislik danışmanı" />}
    {tab === 'profile' && <section className="surface form-shell"><h2>Profilini düzenle</h2><form className="form-grid" onSubmit={(e) => { e.preventDefault(); notify('Profil bilgilerin güncellendi.', 'profile'); }}><label className="field">Son deneme neti<input value={profile.net} onChange={(e) => setProfile({ ...profile, net: e.target.value })} placeholder="Örn. 78,5" /></label><label className="field">Hedef bölüm<input value={profile.target} onChange={(e) => setProfile({ ...profile, target: e.target.value })} /></label><label className="field">Kendini tanıt<textarea value={profile.about} onChange={(e) => setProfile({ ...profile, about: e.target.value })} /></label><button className="button primary">Kaydet</button></form></section>}
  </main>{modal?.type === 'chat' && <Modal title={modal.name} onClose={close}><Conversation thread={`candidate-peer-${modal.name}`} title={`${modal.name} ile sohbet`} /></Modal>}{modal?.type === 'field' && <Modal title={modal.field} onClose={close}><p className="muted">Bu alan için temel dersler, gerekli beceriler, çalışma sektörleri ve örnek kariyer rotaları gösterilir.</p></Modal>}{modal?.type === 'university' && <Modal title={modal.uni.name} onClose={close}><p className="muted">{modal.uni.field} için eğitim planı, hedef sıralama, öğrenci toplulukları ve bölüm bilgisi.</p></Modal>}{modal?.type === 'universityMentors' && <Modal title={`${modal.uni.name} mentorları`} onClose={close}><p className="muted">Bu üniversite için mentor listesi ve iletişim akışı burada yer alır.</p></Modal>}{modal?.type === 'mentor' && <Modal title={modal.mentor.name} onClose={close}><p className="muted">{modal.mentor.job} · {modal.mentor.company}</p><button className="button primary" onClick={() => setModal({ type: 'request', mentor: modal.mentor })}>Mentor isteği gönder</button></Modal>}{modal?.type === 'request' && <Modal title="Mentora not gönder" onClose={close}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); request(modal.mentor); }}><label className="field">Notun<textarea required placeholder="Hedefini ve hangi konuda destek istediğini yaz." /></label><button className="button primary">İsteği gönder</button></form></Modal>}</div>;
}
