import { useEffect, useState } from 'react';
const homeTheme = `
  html, body { background: #030712; color: #f1f5f9; font-family: 'DM Sans', sans-serif; }
  body { background-image: radial-gradient(700px circle at 50% -10%, rgba(6,182,212,.13), transparent 62%), radial-gradient(620px circle at 0% 72%, rgba(13,148,136,.10), transparent 60%); }
  header { background: rgba(3,7,18,.72); border-bottom-color: rgba(255,255,255,.08); backdrop-filter: blur(16px); }
  .logo, .footer-brand .logo { font-family: 'Nunito', sans-serif; font-weight: 900; color: #06b6d4; text-shadow: 0 0 30px rgba(6,182,212,.34); }
  .back-home-btn { font-family: 'DM Sans', sans-serif; font-weight: 700; border-color: rgba(6,182,212,.46); color: #67e8f9; }
  .page-banner { padding-top: 150px; }
  .page-banner h1, .cta-banner-box h2, .detail-modal-title-group h2 { font-family: 'Nunito', sans-serif; font-weight: 900; letter-spacing: -.035em; }
  .page-banner h1 span, .cta-banner-box h2 span, .modal-box h2 span { color: #22d3ee; text-shadow: 0 0 28px rgba(6,182,212,.22); }
  .page-banner p, .section-desc, .discipline-card p, .tab-text p { color: #94a3b8; font-family: 'DM Sans', sans-serif; line-height: 1.75; }
  .showcase-section, .cta-banner-section { position: relative; z-index: 1; }
  .showcase-tabs { border-color: transparent; background: transparent; backdrop-filter: none; box-shadow: none; }
  .tab-btn { font-family: 'DM Sans', sans-serif; font-weight: 700; color: #94a3b8; }
  .tab-btn.active { color: #f1f5f9; background: linear-gradient(135deg, rgba(6,182,212,.22), rgba(13,148,136,.18)); box-shadow: inset 0 0 0 1px rgba(34,211,238,.26), 0 8px 24px rgba(6,182,212,.11); }
  .discipline-card, .showcase-card, .cta-banner-box { background: rgba(15,23,42,.58); border-color: rgba(255,255,255,.10); box-shadow: 0 18px 48px rgba(0,0,0,.25); }
  .discipline-card h3, .tab-text h3 { font-family: 'Nunito', sans-serif; font-weight: 800; color: #f1f5f9; }
  .discipline-card:hover { border-color: rgba(34,211,238,.48); box-shadow: 0 22px 55px rgba(6,182,212,.15); }
  .discipline-tag, .detail-modal-badge { color: #67e8f9; background: rgba(6,182,212,.12); border-color: rgba(34,211,238,.24); }
  .discipline-btn, .primary-register-btn, .submit-btn, .btn-modal-mentor { font-family: 'DM Sans', sans-serif; font-weight: 700; background: linear-gradient(135deg, #0891b2, #0f766e); box-shadow: 0 8px 20px rgba(6,182,212,.16); }
  .discipline-btn:hover, .primary-register-btn:hover, .submit-btn:hover, .btn-modal-mentor:hover { box-shadow: 0 10px 24px rgba(6,182,212,.22); }
  .secondary-login-btn, .btn-modal-close { font-family: 'DM Sans', sans-serif; font-weight: 700; border-color: rgba(34,211,238,.5); color: #67e8f9; }
  footer { background: rgba(3,7,18,.72); border-top-color: rgba(255,255,255,.08); }
  /* Keşif ayrıntılarında daha dingin, tekil bir görsel dil. */
  html, body { background: #0b111a; color: #d7e0e6; font-size: 16px; }
  body { background-image: radial-gradient(760px circle at 50% -15%, rgba(81,132,150,.12), transparent 62%), radial-gradient(640px circle at 0% 72%, rgba(61,104,113,.08), transparent 60%); }
  .page-banner h1 span, .cta-banner-box h2 span, .modal-box h2 span,
  .detail-section-title, .detail-modal-badge { color: #86b9c4; text-shadow: none; }
  .discipline-card, .showcase-card, .cta-banner-box, .discipline-detail-modal-box,
  .detail-section { background: rgba(20,30,43,.82); border-color: rgba(132,170,183,.18); box-shadow: none; }
  .discipline-detail-modal-box { border-color: rgba(112,163,177,.55); }
  .detail-section { border-radius: 18px; }
  .discipline-card:hover { border-color: rgba(134,185,196,.48); box-shadow: 0 12px 30px rgba(0,0,0,.16); }
  .discipline-tag, .detail-modal-badge, .info-pill { background: rgba(74,122,137,.14); border-color: rgba(117,174,188,.45); color: #d1e1e6; }
  .detail-section-title, .detail-section-title i, .info-pill i, .course-card-item i { color: #86b9c4; }
  .detail-section-text, .discipline-card p, .tab-text p, .footer-brand p { color: #c2cdd5; font-size: 16px; line-height: 1.7; }
  .detail-section-title { font-family: 'DM Sans', sans-serif; font-size: 18px; font-weight: 700; }
  .info-pill, .course-card-item, .discipline-tag, .tab-btn, .discipline-btn,
  .primary-register-btn, .secondary-login-btn, .submit-btn, .btn-modal-mentor, .btn-modal-close {
    font-family: 'DM Sans', sans-serif; font-size: 15px; font-weight: 600;
  }
  .detail-modal-title-group h2 { font-size: clamp(28px, 3vw, 36px); color: #edf3f5; text-shadow: none; }
  .discipline-card h3, .tab-text h3 { font-size: 21px; line-height: 1.25; }
  .discipline-btn, .primary-register-btn, .submit-btn, .btn-modal-mentor { background: linear-gradient(135deg, #527f8c, #426d70); box-shadow: none; color: #f2f7f8; }
  .discipline-btn:hover, .primary-register-btn:hover, .submit-btn:hover, .btn-modal-mentor:hover { background: linear-gradient(135deg, #608d98, #4c787a); box-shadow: 0 8px 20px rgba(32,62,72,.18); }
  .secondary-login-btn, .btn-modal-close { border-color: rgba(134,185,196,.56); color: #b8d5dc; background: transparent; }
  .close-modal { background: transparent; color: #aebfc7; border: 0; font-size: 28px; width: 44px; height: 44px; }
  .close-modal:hover { color: #eef5f6; background: rgba(134,185,196,.1); }
  .modal-overlay { overflow-y: auto; align-items: flex-start; padding: 48px 20px; scrollbar-width: none; }
  .modal-overlay::-webkit-scrollbar { display: none; }
  .discipline-detail-modal-box { max-height: none; overflow: visible; margin: 0 auto; }
`;
const disciplines = [
  ['yazilim', 'fa-laptop-code', 'Yazılım & AI', 'Yazılım / Bilgisayar Müh.', 'Backend, Frontend, Yapay Zeka, Siber Güvenlik ve Mobil geliştirme kariyer yollarını keşfet.'],
  ['elektrik', 'fa-bolt', 'Enerji & Sistem', 'Elektrik-Elektronik Müh.', 'Devre tasarımı, gömülü sistemler, yenilenebilir enerji ve otomasyon teknolojilerini incele.'],
  ['makine', 'fa-gears', 'Tasarım & Üretim', 'Makine Mühendisliği', 'CAD/CAM tasarımı, imalat, robotik, mekatronik ve termodinamik alt alanlarını gör.'],
  ['endustri', 'fa-sitemap', 'Veri & Yönetim', 'Endüstri Mühendisliği', 'Süreç optimizasyonu, tedarik zinciri, veri analitiği ve üretim yönetimi alanlarını keşfet.'],
  ['insaat', 'fa-compass-drafting', 'Yapı & Proje', 'İnşaat Mühendisliği', 'Akıllı yapılar, altyapı projeleri, geoteknik ve deprem dayanımlı bina tasarımını incele.'],
  ['kimya', 'fa-flask', 'Proses & Malzeme', 'Kimya Mühendisliği', 'Proses tasarımı, batarya teknolojileri, polimer ve sentez sistemleri kariyer alanları.'],
  ['biyomedikal', 'fa-heart-pulse', 'Sağlık & Medikal', 'Biyomedikal Mühendisliği', 'Tıbbi cihaz tasarımı, biyomekanik, yapay organlar ve sağlık teknolojilerini incele.'],
  ['havacilik', 'fa-plane', 'Savunma & Uzay', 'Havacılık ve Uzay Müh.', 'Aerodinamik, İHA/SİHA sistemleri, jet motorları ve uydu teknolojilerini keşfet.'],
  ['gemi', 'fa-ship', 'Denizcilik', 'Gemi & Deniz Teknolojisi', 'Gemi tasarımı, marin hidrodinamik, marinalar ve açık deniz yapılarını incele.'],
];
const detail = {
  yazilim: ['Yazılım / Bilgisayar Müh.', 'Yazılım & AI', 'fa-laptop-code', 'Yazılım ve Bilgisayar Mühendisliği; dijital çağın mimarisini oluşturan kodlar, yapay zeka modelleri, veri yapıları ve güvenlik altyapılarını tasarlar.', ['Backend & API Architecture', 'Frontend & UI/UX Design', 'Yapay Zeka & Derin Öğrenme', 'Siber Güvenlik & Kriptoloji', 'Mobil Uygulama'], ['Python', 'JavaScript / TypeScript', 'React / Next.js', 'Docker & Kubernetes', 'SQL / NoSQL'], ['Veri Yapıları & Algoritmalar', 'Nesne Yönelimli Programlama', 'Veritabanı Yönetimi', 'İşletim Sistemleri'], 'Yüksek talep, uzaktan çalışma ve global iş fırsatları.'],
  elektrik: ['Elektrik-Elektronik Müh.', 'Enerji & Sistem', 'fa-bolt', 'Elektrik-Elektronik Mühendisliği; mikroçiplerden yenilenebilir enerji santrallerine, haberleşme sistemlerinden gömülü yazılımlara kadar elektroniğin gücünü somut çözümlere dönüştürür.', ['Gömülü Sistemler', 'Mikroelektronik & Çip Tasarımı', 'Haberleşme & Sinyal İşleme', 'Güç Elektroniği', 'Endüstriyel Otomasyon & PLC'], ['C / C++', 'MATLAB / Simulink', 'Altium Designer', 'KiCad', 'Verilog / VHDL', 'Python'], ['Devre Teorisi', 'Elektronik Devreler', 'Sinyaller ve Sistemler', 'Mikroişlemciler', 'Kontrol Sistemleri'], 'Enerji dönüşümü, otomasyon, savunma teknolojileri ve akıllı cihazlar bu alanın öne çıkan çalışma eksenleridir.'],
  makine: ['Makine Mühendisliği', 'Tasarım & Üretim', 'fa-gears', 'Makine Mühendisliği; hareket eden sistemlerin kuvvet, ısı, akışkan ve malzeme analizini yaparak fikirleri güvenli ve üretilebilir fiziksel ürünlere dönüştürür.', ['Mekanik Tasarım & CAD', 'İmalat & Üretim Yöntemleri', 'Termodinamik & Isı Transferi', 'Mekatronik & Robotik', 'Otomotiv Sistemleri'], ['SolidWorks', 'CATIA', 'AutoCAD', 'ANSYS', 'MATLAB', 'CNC G-Code'], ['Statik & Dinamik', 'Mukavemet', 'Termodinamik', 'Akışkanlar Mekaniği', 'Makine Elemanları', 'İmal Usulleri'], 'Üretim, otomotiv, enerji, savunma ve robotik; makine mühendislerinin yaygın olarak görev aldığı sektörlerdir.'],
  endustri: ['Endüstri Mühendisliği', 'Veri & Yönetim', 'fa-sitemap', 'Endüstri Mühendisliği; insan, makine, bilgi ve finans kaynaklarını birlikte ele alır; karmaşık süreçlerin verimliliğini, kalitesini ve sürdürülebilirliğini geliştirir.', ['Yöneylem Araştırması & Optimizasyon', 'Veri Analitiği', 'Tedarik Zinciri & Lojistik', 'Yalın Üretim', 'ERP & Süreç Yönetimi'], ['Python / R', 'SQL', 'SAP / ERP', 'Power BI', 'Tableau', 'Advanced Excel'], ['Yöneylem Araştırması', 'İstatistik ve Olasılık', 'Üretim Planlama', 'Kalite Yönetimi', 'Benzetim', 'Maliyet Analizi'], 'Finans, e-ticaret, lojistik, üretim ve teknoloji şirketlerinde veri odaklı operasyon ve strateji rolleri öne çıkar.'],
  insaat: ['İnşaat Mühendisliği', 'Yapı & Proje', 'fa-compass-drafting', 'İnşaat Mühendisliği; binaların, köprülerin, ulaşım ağlarının ve altyapı sistemlerinin güvenli, dayanıklı ve yaşanabilir biçimde tasarlanması ve inşa edilmesini sağlar.', ['Yapı Statiği & Deprem Mühendisliği', 'Geoteknik & Zemin Mekaniği', 'Ulaştırma', 'Hidrolik & Su Yapıları', 'Proje Yönetimi & BIM'], ['AutoCAD', 'SAP2000', 'ETABS', 'Revit', 'Primavera P6', 'MS Project'], ['Yapı Statiği', 'Betonarme', 'Zemin Mekaniği', 'Hidrolik', 'Çelik Yapılar', 'Şantiye Yönetimi'], 'Kentsel dönüşüm, altyapı yatırımları, dayanıklı yapı tasarımı ve BIM tabanlı proje yönetimi alanın başlıca çalışma konularıdır.'],
  kimya: ['Kimya Mühendisliği', 'Proses & Malzeme', 'fa-flask', 'Kimya Mühendisliği; hammaddeleri güvenli, verimli ve sürdürülebilir proseslerle ilaç, batarya, polimer, gıda ve kimyasal ürünlere dönüştüren disiplindir.', ['Proses Tasarımı & Simülasyonu', 'Batarya & Enerji Depolama', 'Polimer & Nanoteknoloji', 'Petrokimya', 'İlaç & Biyoteknoloji'], ['Aspen Plus / HYSYS', 'ChemCAD', 'MATLAB', 'COMSOL', 'Minitab', 'LabVIEW'], ['Kütle ve Isı Transferi', 'Kimyasal Reaksiyon Mühendisliği', 'Termodinamik', 'Proses Kontrol', 'Ayırma İşlemleri'], 'Enerji depolama, sürdürülebilir üretim, ileri malzemeler ve ilaç geliştirme, kimya mühendisliği için önemli gelişim alanlarıdır.'],
  biyomedikal: ['Biyomedikal Mühendisliği', 'Sağlık & Medikal', 'fa-heart-pulse', 'Biyomedikal Mühendisliği; tıbbi cihazlar, biyosinyal işleme, protezler ve sağlık yazılımları geliştirerek tanı ve tedavi süreçlerini destekler.', ['Tıbbi Görüntüleme', 'Biyomekanik & Protez Tasarımı', 'Biyosinyal İşleme', 'Klinik Mühendislik', 'Biyomalzeme & Doku Mühendisliği'], ['MATLAB / Simulink', 'LabVIEW', 'Python', 'DICOM Araçları', 'SolidWorks', 'SPSS'], ['Biyomedikal Sinyal İşleme', 'Tıbbi Cihaz Elektroniği', 'Biyomekanik', 'Anatomi & Fizyoloji', 'Biyomateryaller'], 'Yaşlanan nüfus, uzaktan sağlık çözümleri ve dijital tanı teknolojileri; medikal teknolojilerde disiplinlerarası uzmanlığı değerli kılar.'],
  havacilik: ['Havacılık ve Uzay Müh.', 'Savunma & Uzay', 'fa-plane', 'Havacılık ve Uzay Mühendisliği; uçak, İHA, uydu ve uzay araçlarının aerodinamik, itki, kontrol ve yapısal tasarımını geliştirir.', ['Aerodinamik & CFD', 'İtki Sistemleri', 'Uçuş Dinamiği & Kontrol', 'Aviyonik & Otonom Sistemler', 'Uydu ve Uzay Yapıları'], ['OpenFOAM', 'ANSYS Fluent', 'CATIA', 'MATLAB / Simulink', 'ROS', 'C++ / Python'], ['Aerodinamik', 'Uçuş Mekaniği', 'İtki Sistemleri', 'Gaz Dinamiği', 'Uçak Yapıları', 'Aviyonik Sistemler'], 'Savunma, sivil havacılık, uydu teknolojileri ve otonom sistemler; yoğun doğrulama ve güvenlik standartlarıyla çalışan başlıca alanlardır.'],
  gemi: ['Gemi & Deniz Teknolojisi', 'Denizcilik', 'fa-ship', 'Gemi ve Deniz Teknolojisi Mühendisliği; gemi, yat, deniz platformu ve kıyı yapılarının tasarımı, üretimi ve işletme performansını ele alır.', ['Gemi Tasarımı & Hidrodinamik', 'Tersane Üretim Yönetimi', 'Yat Tasarımı', 'Açık Deniz Yapıları', 'Marin Sevk Sistemleri'], ['Maxsurf', 'Rhino 3D', 'AutoCAD', 'ANSYS Hydrodynamics', 'SolidWorks', 'Python'], ['Gemi Hidrodinamiği', 'Gemi Statiği ve Sevk', 'Tersane Organizasyonu', 'Deniz Yapıları', 'Marin Motorlar'], 'Tersaneler, deniz taşımacılığı, yat üretimi ve offshore enerji projeleri; deniz teknolojilerinin temel uygulama alanlarıdır.'],
};
function Notice({ children, close, className = 'modal-box' }) { return <div className="modal-overlay active" onMouseDown={(e) => e.target === e.currentTarget && close()}><div className={className}><button className="close-modal" onClick={close} aria-label="Kapat">×</button>{children}</div></div>; }

export default function Explore() {
  const requestedTab = new URLSearchParams(location.search).get('tab');
  const [tab, setTab] = useState(['disciplines', 'mentorship', 'opportunities'].includes(requestedTab) ? requestedTab : 'disciplines');
  const [modal, setModal] = useState(null);
  const [login, setLogin] = useState({ email: '', sifre: '' });
  const selected = detail[modal] ?? [disciplines.find((item) => item[0] === modal)?.[3], disciplines.find((item) => item[0] === modal)?.[2], disciplines.find((item) => item[0] === modal)?.[1], disciplines.find((item) => item[0] === modal)?.[4], [], [], [], ''];
  useEffect(() => { document.body.style.overflow = modal ? 'hidden' : ''; return () => { document.body.style.overflow = ''; }; }, [modal]);
  async function signIn(e) { e.preventDefault(); const response = await fetch('/api/giris-yap', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(login) }); const data = await response.json(); if (!response.ok) return alert(data.error); Object.entries({ kullaniciDisiplin: data.department, kullaniciRolu: data.rol, kullaniciDurumu: data.durum, kullaniciAdi: data.kullanici_adi, kullaniciOkul: data.okul || '', kullaniciBolum: data.bolum || '', kullaniciSinif: data.sinif || '', kullaniciIsYeri: data.is_yeri || '', kullaniciDeneyim: data.deneyim || '' }).forEach(([key, value]) => localStorage.setItem(key, value)); location.assign(data.rol === 'mentor' ? '/panel/mentor' : data.durum === 'lise_ogrenci' ? '/panel/aday' : '/panel/ogrenci'); }
  return <><header><a href="/" className="logo">EngineersPath</a><a href="/" className="back-home-btn"><i className="fa-solid fa-arrow-left" /> Ana Sayfaya / Panele Dön</a></header>
    <main><section className="page-banner"><h1>Mühendislik Platformu <span>Keşif Alanı</span> 🚀</h1><p>EngineersPath'in sunduğu tüm akademik, kariyer ve rehberlik imkanlarını inceleyin.</p></section>
    <section className="showcase-section"><div className="showcase-tabs"><button className={'tab-btn ' + (tab === 'disciplines' ? 'active' : '')} onClick={() => setTab('disciplines')}><i className="fa-solid fa-compass-drafting" /> Mühendislik Disiplinleri</button><button className={'tab-btn ' + (tab === 'mentorship' ? 'active' : '')} onClick={() => setTab('mentorship')}><i className="fa-solid fa-user-graduate" /> Birebir Mentorluk</button><button className={'tab-btn ' + (tab === 'opportunities' ? 'active' : '')} onClick={() => setTab('opportunities')}><i className="fa-solid fa-briefcase" /> Staj & Proje Fırsatları</button></div>
    {tab === 'disciplines' && <div className="showcase-tab-content active"><div style={{ textAlign: 'center', marginBottom: 25 }}><h3 style={{ fontSize: 30, color: 'white', marginBottom: 8 }}><i className="fa-solid fa-compass-drafting" style={{ color: '#06b6d4' }} /> Tüm Mühendislik Disiplinleri</h3><p style={{ color: '#94a3b8', fontSize: 16 }}>Geleceğin dünyasını şekillendiren mühendislik dallarını keşfet ve uzmanlık alanını belirle.</p></div><div className="discipline-grid">{disciplines.map(([key, icon, tag, title, text]) => <article className="discipline-card" key={key}><div><div className="card-header-flex"><div className="card-icon"><i className={'fa-solid ' + icon} /></div><span className="discipline-tag">{tag}</span></div><h3>{title}</h3><p>{text}</p></div><button className="discipline-btn" onClick={() => setModal(key)}>Detaylı İncele <i className="fa-solid fa-arrow-right" /></button></article>)}</div></div>}
    {tab !== 'disciplines' && <Showcase type={tab} openNotice={() => setModal('auth')} />}</section>
    <section className="cta-banner-section"><div className="cta-banner-box"><h2>Geleceğin Mühendisi Olmaya <span>Hazır Mısın?</span> 🚀</h2><p>Binlerce mühendis adayı ve deneyimli mentor EngineersPath topluluğunda buluşuyor. Sen de hemen yerini al, kariyer yolculuğunda bir adım öne geç!</p><div className="cta-btn-group"><a href="/kayit" className="primary-register-btn"><i className="fa-solid fa-user-plus" /> Hemen Ücretsiz Kayıt Ol</a><button className="secondary-login-btn" onClick={() => setModal('auth')}><i className="fa-solid fa-right-to-bracket" /> Hesabın Var Mı? Giriş Yap</button></div></div></section></main>
    <footer><div className="footer-container"><div className="footer-brand"><a href="/" className="logo">EngineersPath</a><p>Mühendislik Kariyer Yolculuğunuzdaki Güvenilir Rehberiniz.</p></div><ul className="footer-links"><li><a href="/kesfet">Keşfet</a></li><li><a href="/kesfet?tab=disciplines">Disiplinler</a></li><li><a href="/kayit">Kayıt Ol</a></li></ul><div className="footer-socials"><a href="#"><i className="fa-brands fa-linkedin-in" /></a><a href="#"><i className="fa-brands fa-github" /></a><a href="#"><i className="fa-brands fa-x-twitter" /></a><a href="#"><i className="fa-brands fa-instagram" /></a></div></div><div className="footer-bottom-line">© 2026 EngineersPath. Tüm hakları saklıdır. Mühendislik tutkusuyla tasarlandı. ⚙️✨</div></footer>
    {modal === 'auth' && <Notice close={() => setModal(null)}><div style={{ textAlign: 'center' }}><div style={{ fontSize: 55, color: '#06b6d4', marginBottom: 15 }}><i className="fa-solid fa-user-lock" /></div><h2>Bu Özellik İçin <span>Üye Olmalısınız!</span> 🔒</h2><p>Mentorlarla birebir görüşmek, CV incelemesi talep etmek ve ilanlara başvurmak için üyeliğiniz bulunmalıdır.</p><div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}><button className="submit-btn" onClick={() => setModal('login')}>Hesabın Var Mı? Giriş Yap</button><a href="/kayit" className="submit-btn">Ücretsiz Kayıt Ol</a></div></div></Notice>}
    {modal === 'login' && <Notice close={() => setModal(null)}><h2>Tekrar <span>Hoş Geldin!</span></h2><form onSubmit={signIn}><div className="form-group"><label htmlFor="exploreLoginEmail">E-posta Adresi</label><input id="exploreLoginEmail" type="email" required value={login.email} onChange={(e) => setLogin({ ...login, email: e.target.value })} /></div><div className="form-group"><label htmlFor="exploreLoginPassword">Şifre</label><input id="exploreLoginPassword" type="password" required value={login.sifre} onChange={(e) => setLogin({ ...login, sifre: e.target.value })} /></div><button className="submit-btn">Giriş Yap</button></form></Notice>}
    {modal && modal !== 'auth' && <Notice close={() => setModal(null)} className="discipline-detail-modal-box"><div className="detail-modal-header"><div className="detail-modal-icon"><i className={'fa-solid ' + selected[2]} /></div><div className="detail-modal-title-group"><h2>{selected[0]}</h2><span className="detail-modal-badge">{selected[1]}</span></div></div><Detail title="Genel Bakış & Misyon" icon="fa-circle-info"><p className="detail-section-text">{selected[3]}</p></Detail><Detail title="Uzmanlık Alanları & Alt Branşlar" icon="fa-route"><div className="pill-container">{selected[4].map((item) => <span className="info-pill" key={item}><i className="fa-solid fa-check" /> {item}</span>)}</div></Detail><Detail title="Temel Araçlar & Teknolojiler" icon="fa-screwdriver-wrench"><div className="pill-container">{selected[5].map((item) => <span className="info-pill" key={item}><i className="fa-solid fa-code" /> {item}</span>)}</div></Detail><Detail title="Temel Lisans Dersleri" icon="fa-graduation-cap"><div className="course-grid">{selected[6].map((item) => <div className="course-card-item" key={item}><i className="fa-solid fa-book" /> {item}</div>)}</div></Detail><Detail title="Sektör Görünümü & Gelecek Beklentisi" icon="fa-chart-line"><p className="detail-section-text">{selected[7]}</p></Detail><div className="detail-modal-footer"><button className="btn-modal-mentor" onClick={() => setModal('auth')}><i className="fa-solid fa-comments" /> Mentorları Keşfet</button><button className="btn-modal-close" onClick={() => setModal(null)}>Kapat</button></div></Notice>}
  </>;
}
function Detail({ title, icon, children }) { return <div className="detail-section"><div className="detail-section-title"><i className={'fa-solid ' + icon} /> {title}</div>{children}</div>; }
function Showcase({ type, openNotice }) { const mentor = type === 'mentorship'; const content = mentor ? ['Tecrübeli Mühendislerden Rehberlik', 'Sektörde çalışan kıdemli mühendislerle eşleş. CV incelemesi, mülakat simülasyonu ve kariyer tavsiyeleri ile hedeflerine daha hızlı ulaş.', ['Doğrudan Birebir Canlı Görüşme', 'Şirket Kültürleri & Mülakat İpuçları', 'Onaylı ve Deneyimli Mentor Kadrosu'], ['150+', '4.9 / 5', '1.200+', '7/24'], ['Aktif Mentor', 'Puanlama', 'Görüşme', 'Erişim']] : ['Gerçek Projeler & Staj İlanları', 'Öğrencilik yıllarında portfolyonu güçlendir. Topluluk projelerine katıl, şirketlerin staj ve yeni mezun ilanlarını yakından takip et.', ['Doğrulanmış Şirket İlanları', 'Açık Kaynak Topluluk Projeleri', 'Hackathon ve Yarışma Duyuruları'], ['85+', '300+', '40+', 'Haftalık'], ['Partner Şirket', 'Aktif İlan', 'Takım Projesi', 'Güncelleme']]; return <div className="showcase-card showcase-tab-content active"><div className="tab-text"><h3>{content[0]}</h3><p>{content[1]}</p><ul className="feature-bullets">{content[2].map((item) => <li key={item}><i className="fa-solid fa-check" /> {item}</li>)}</ul>{mentor && <button className="primary-register-btn" onClick={openNotice}>Mentor Randevusu Al (Üye Ol)</button>}</div><div className="tab-visual"><div className="visual-stat-grid">{content[3].map((value, index) => <div className="stat-box" key={value}><div className="number">{value}</div><div className="label">{content[4][index]}</div></div>)}</div></div></div>; }
