import { useState } from 'react';
const blank = { name: '', email: '', status: '', school: '', department: '', level: '', workplace: '', experience: '', password: '' };
export default function Register() {
  const [form, setForm] = useState(blank); const [message, setMessage] = useState('');
  const update = (key) => (e) => setForm({ ...form, [key]: e.target.value });
  const student = form.status === 'uni_ogrenci'; const graduate = form.status === 'uni_mezun'; const mentor = form.status === 'mentor'; const highSchool = form.status === 'lise_ogrenci';
  async function submit(e) {
    e.preventDefault(); setMessage('');
    const departmentName = form.department.toLocaleLowerCase('tr');
    const department = /tıp|doktor|sağlık/.test(departmentName) ? 'med' : /hukuk|adalet/.test(departmentName) ? 'law' : /işletme|iktisat|finans/.test(departmentName) ? 'business' : 'tech';
    const response = await fetch('/api/kayit-ol', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kullanici_adi: form.name, email: form.email, department, rol: mentor ? 'mentor' : 'ogrenci', durum: form.status, okul: form.school || null, bolum: form.department || null, sinif: form.level || null, is_yeri: form.workplace || null, deneyim: form.experience || null, sifre: form.password }) });
    const data = await response.json();
    if (!response.ok) return setMessage(data.error);
    Object.entries({ kullaniciDisiplin: department, kullaniciRolu: mentor ? 'mentor' : 'ogrenci', kullaniciDurumu: form.status, kullaniciAdi: form.name, kullaniciOkul: form.school, kullaniciBolum: form.department, kullaniciSinif: form.level, kullaniciIsYeri: form.workplace, kullaniciDeneyim: form.experience }).forEach(([k, v]) => localStorage.setItem(k, v || ''));
    setMessage(data.message); setTimeout(() => { location.assign(mentor ? '/panel/mentor' : highSchool ? '/panel/aday' : '/panel/ogrenci'); }, 700);
  }
  return <><a href="/" className="back-home"><i className="fa-solid fa-arrow-left" /> Ana Sayfaya Dön</a><main className="register-container"><h2>Aramıza <span>Katıl & Keşfet!</span> 🚀</h2><form onSubmit={submit}><div className="form-row"><Field label="Ad Soyad"><input required value={form.name} onChange={update('name')} placeholder="Ad Soyad" /></Field><Field label="E-posta Adresi"><input required type="email" value={form.email} onChange={update('email')} placeholder="ornek@universite.edu.tr" /></Field></div><Field label="Eğitim / Profesyonel Durum"><select required value={form.status} onChange={update('status')}><option value="" disabled>Seçiniz...</option><option value="uni_ogrenci">Üniversite Öğrencisi</option><option value="lise_ogrenci">Lise Öğrencisi / Mezunu</option><option value="uni_mezun">Üniversite Mezunu</option><option value="mentor">Mentörlük Yapmak İstiyorum</option></select></Field>{(student || graduate || mentor || highSchool) && <Field label={highSchool ? 'Lise / Mezun Olunan Lise' : graduate || mentor ? 'Mezun Olduğunuz Okul' : 'Okul Adı'}><input required value={form.school} onChange={update('school')} /></Field>}{(student || graduate || mentor) && <Field label={graduate || mentor ? 'Mezun Olduğunuz Bölüm' : 'Bölüm Adı'}><input required value={form.department} onChange={update('department')} /></Field>}{student && <Field label="Sınıf / Seviye"><select required value={form.level} onChange={update('level')}><option value="" disabled>Seviye seçiniz...</option>{['Hazırlık', '1. Sınıf', '2. Sınıf', '3. Sınıf', '4. Sınıf'].map((item, i) => <option value={i === 0 ? '0' : String(i)} key={item}>{item}</option>)}</select></Field>}{mentor && <><Field label="Çalıştığınız İş Yeri / Kurum"><input required value={form.workplace} onChange={update('workplace')} placeholder="Örn: teknoloji şirketi" /></Field><Field label="Deneyim Süresi"><select required value={form.experience} onChange={update('experience')}><option value="" disabled>Süre seçiniz...</option>{['0 - 1 Yıl', '1 - 3 Yıl', '3 - 5 Yıl', '5 - 10 Yıl', '10+ Yıl'].map((item) => <option key={item}>{item}</option>)}</select></Field></>}<Field label="Şifre Oluştur"><input required type="password" minLength="6" value={form.password} onChange={update('password')} placeholder="En az 6 karakter" /></Field><button className="submit-btn">Kayıt İşlemini Tamamla</button>{message && <p className={message.includes('Başarı') || message.includes('Harika') ? 'form-success' : 'form-error'}>{message}</p>}</form></main></>;
}
function Field({ label, children }) { return <div className="form-group full-width"><label>{label}</label>{children}</div>; }
